---
- name: Ensure HAProxy is installed.
  apt: name=haproxy state=present

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: false

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
